### ISSUE TITLE
player and trader inventory not loading

### ISSUE THREAD

**Issue by Garyyy77** [space-commits/SPT-Realism-Mod-Client#3] opened 2023-06-01 00:49 UTC
im guessing its this mod, since its the only thing red in the console
the only thing i changed in the config is disabling the recoil overhaul

heres an image of it:
https://imgur.com/a/Sl330Om
https://imgur.com/a/zfVMYg9

heres my console:
the lines which are red in the console are marked **bold**

Commit hash: 92c2da785bdc1cf36eb4d4c4ef9ce0e64c73553b
┌─────────────────────────────────────┐
│ SPT-AKI 3.5.7                       │
│ https://discord.sp-tarkov.com       │
│                                     │
│ This work is free of charge         │
│ If you paid money, you were scammed │
│ Commercial use is prohibited        │
└─────────────────────────────────────┘
ModLoader: loading 28 mods...
Mod Basuro-zerotimes is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
Mod Faupi-MunitionsExpert is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
Mod Faupi-HideoutArchitect is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
Mod KMC-CORE is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
Mod KMC-GEAR is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
Mod KMC-WEAPONS is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
Mod Lua-FleaMarketPriceUpdater is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
Mod Lua-SpawnRework is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
Mod Nightingale-broker_trader is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
Mod: Boop&#39;s Quest Zone API version: 1.0.0 by: Boop loaded
Mod: AKGUYmod version: 3.5.2 by: Fershte loaded
Mod: armalite-reloaded version: 3.5.2 by: Fershte loaded
Mod: zerotimes version: 2.0.0 by: Basuro loaded
Mod: MunitionsExpert version: 1.7.1 by: Faupi loaded
Mod: GearGal version: 3.5.2 by: Fershte loaded
Mod: TheGoblinKing version: 1.0.5 by: RockaHorse and Tip loaded
Mod: HideoutArchitect version: 1.7.1 by: Faupi loaded
Mod: CORE version: 3.0.1 by: KMC loaded
Mod: GEAR version: 3.0.0 by: KMC loaded
Mod: WEAPONS version: 3.0.1 by: KMC loaded
Mod: FleaMarketPriceUpdater version: 3.1.2 by: Lua loaded
Mod: SpawnRework version: 2.1.8 by: Lua loaded
Mod: broker_trader version: 1.3.1 by: Nightingale loaded
Mod: EyesOfATrader version: 1.3.0 by: Platinum loaded
Mod: Priscilu version: 2.3.7 by: Reis loaded
Mod: Call of Duty: Warzone - CTSFO I version: 4.2.0 by: SamSWAT loaded
Mod: GIAT FAMAS F1 version: 1.0.0 by: SamSWAT loaded
Mod: L85A2 British Assault Rifle 5.56x45 version: 1.0.0 by: SamSWAT loaded
Mod: Benelli M4 Super 90 ( M1014 ) version: 2.0.7 by: SamSWAT loaded
Mod: Contract Wars VAL MOD3 version: 1.0.0 by: SamSWAT loaded
Mod: Molot Vepr-12 version: 1.0.0 by: SamSWAT loaded
Mod: SPT Realism Mod TEST RELEASE version: 0.8.0 by: Fontaine loaded
Mod: Virtuals Custom Quest Loader version: 1.2.0 by: Virtual loaded
Mod: Elcan C79A2 version: 1.0.0 by: SamSWAT loaded
Mod: Holosun HS507C ACSS version: 1.0.0 by: SamSWAT loaded
Mod: Leupold D-EVO version: 1.0.0 by: SamSWAT loaded
Mod: RARDE SUSAT version: 1.0.0 by: SamSWAT loaded
[broker_trader 1.3.1] preAki Loading...
[broker_trader 1.3.1] Registering BrokerTraderRouter...
[broker_trader 1.3.1] preAki Loaded
Server: executing startup callbacks...
Importing database...
Database import finished
Insurance interval is 60
Insurance return chance is 80%
Bitcoin farm level 1 bonus changed to 100
Bitcoin farm level 2 bonus changed to 150
Bitcoin farm level 3 bonus changed to 250
Craft '5d1b33a686f7742523398398' not modified
Craft '59faff1d86f7746c51718c9c' not modified
Scav '6271093e621b0a76055cd61e' overridden to 40 seconds
Scav '62710974e71632321e5afd5f' overridden to 10 seconds
Scav '62710a0e436dcc0b9c55f4ec' overridden to 50 seconds
Scav '62710a69adfbd4354d79c58e' overridden to 30 seconds
Scav '62710a8c403346379e3de9be' overridden to 20 seconds
Scav cooldown set to 120 seconds
[GoblinKing] Items rebalanced for more realism
[GoblinKing] Goblin King Active
[GoblinKing] Please report bugs in the mod's comments or support thread.
[GoblinKing] Thanks for playing - Rockahorse and Tip
Loading: Lua-FleaMarketPriceUpdater 3.1.2 [Disabled]
Loading: Lua-SpawnRework 2.1.8
[broker_trader 1.3.1] postDb Loading...
[broker_trader 1.3.1] postDb Loaded
**Realism Mod: RealismMod.dll is present at path: C:\Users\Baris Sefil\Desktop\spt\BepInEx\plugins\RealismMod.dll, but 'Recoil, Ballistics and Attachment Overhaul' is disabled, plugin will disable itself.**
GKQ16-20Locale.json loaded from en locale
GKQLocale.json loaded from en locale
GKQ16-20Locale.json loaded from ge locale
GKQLocale.json loaded from ge locale
GKQ16-20Locale.json loaded from ru locale
GKQLocale.json loaded from ru locale
GKQ.json loaded from Virtual's Custom Quest Loader
GKQ16-20.json loaded from Virtual's Custom Quest Loader
20 quests total loaded from Virtual's Custom Quest Loader
20 images total loaded from Virtual's Custom Quest Loader
[broker_trader 1.3.1] Initialized supported traders range. 8 traders are being supported.
[broker_trader 1.3.1] Generating ragfair price look-up table...
[broker_trader 1.3.1] Look-up table successfully generated.
[broker_trader 1.3.1] Loaded trader meta data from database.
[broker_trader 1.3.1] Loaded currency buy rates from config.
Started webserver at http://127.0.0.1:6969
Started websocket at ws://127.0.0.1:6969
Server is running Happy playing!!
[Eyes of a Trader]: Success! Found 2853 items to update.
[Client Request] /launcher/server/connect
[Client Request] /launcher/ping
[Client Request] /launcher/server/version
[Client Request] /files/launcher/bg.png
[Client Request] /launcher/profiles
[Client Request] /launcher/ping
[Client Request] /launcher/profile/login
[Client Request] /launcher/profile/register
Profile changes saved
[Client Request] /launcher/profile/login
[Client Request] /launcher/profile/get
[Client Request] /launcher/profile/info
[Client Request] /launcher/server/version
[Client Request] /launcher/profile/login
[Client Request] /launcher/profile/get
[Client Request] /launcher/profile/info
[Client Request] /launcher/server/version
[Client Request] /launcher/profile/compatibleTarkovVersion
[Client Request] /launcher/profile/login
[Client Request] /launcher/profile/get
[Client Request] /launcher/profile/info
[Client Request] /launcher/server/version
[Client Request] /broker-trader/get/mod-config
[Client Request] /broker-trader/get/currency-base-prices
[Client Request] /broker-trader/get/supported-trader-ids
[Client Request] /broker-trader/get/item-ragfair-price-table
[Client Request] /client/items/prices/54cb50c76803fa8b248b4571
[Client Request] /client/items/prices/54cb57776803fa99248b456e
[Client Request] /client/items/prices/579dc571d53a0658a154fbec
[Client Request] /client/items/prices/58330581ace78e27b8b10cee
[Client Request] /client/items/prices/5935c25fb3acc3127c3d8cd9
[Client Request] /client/items/prices/5a7c2eca46aef81a7ca2145d
[Client Request] /client/items/prices/5ac3b934156ae10c4430e83c
[Client Request] /client/items/prices/5c0647fdd443bc2504c2d371
[Client Request] /broker-trader/get/ragfair-sell-rep-gain
[Client Request] /HideoutArchitect/GetInfo
[Client Request] /singleplayer/bundles
[Client Request] /RealismMod/GetInfo
[Client Request] /singleplayer/settings/version
[Client Request] /client/game/start
[Client Request] /client/menu/locale/en
[Client Request] /client/game/version/validate
**Realism Mod: Error Checking Player Profile: TypeError: Cannot read properties of undefined (reading '_parent')**
Realism Mod: Backup path does not exist, creating folder....
Realism Mod: Profile backup executed successfully: _2023-06-01_02-24-32
[Client Request] /client/languages
[Client Request] /client/game/config
[Client Request] /client/items
[Client Request] /client/customization
[Client Request] /client/globals
[Client Request] /client/trading/api/traderSettings
[Client Request] /client/settings
[Client Request] /client/game/profile/list
[Client Request] /client/locale/en
[Client Request] /client/account/customization
[Client Request] /client/locale/ru
[Client Request] /client/locale/ge
[Client Request] /client/locale/fr
Profile changes saved
[Client Request] /client/game/profile/nickname/reserved
[Client Request] /client/game/profile/nickname/validate
[Client Request] /client/game/profile/create
Profile changes saved
Profile changes saved
Realism Mod: New Profile Meds And Hydration/Energy Adjusted
Realism Mod: New Profile Meds And Hydration/Energy Adjusted
Realism Mod: New Profile Health Has Been Adjusted
Realism Mod: New Profile Modified
[Client Request] /client/game/profile/list
[Client Request] /client/game/profile/select
[Client Request] /client/profile/status
[Client Request] /client/weather
[Client Request] /client/locations
Loaded spawn patter: Lua-Default. Good Luck!

  BIGMAP
  MaxBotPerZone: 20     MaxAlive: 25
------------------------- Boss -------------------------
 [¿] Secret
------------------------- PMC --------------------------
 [1] 1-5 @ PMC [USEC Chance: 50]
 [2] 1-5 @ PMC [USEC Chance: 50]
 [3] 1-5 @ PMC [USEC Chance: 50]
 [4] 1-5 @ PMC [USEC Chance: 50]
 [5] 1-5 @ PMC [USEC Chance: 50]
 [6] 1-5 @ PMC [USEC Chance: 50]
 [7] 1-5 @ PMC [USEC Chance: 50]
 [8] 1-5 @ PMC [USEC Chance: 50]
------------------------- Scav -------------------------
 [9] 1-3 @ Scav
 [10] 1-3 @ Scav
 [11] 1-3 @ Scav
 [12] 1-3 @ Scav
 [13] 1-3 @ Scav
 [14] 1-3 @ Scav
 [15] 1-3 @ Scav
 [16] 1-3 @ Scav
 [17] 1-3 @ Scav
 [18] 1-3 @ Scav
 [19] 1-3 @ Scav
 [20] 1-3 @ Scav
---------------------- Sniper Scav ---------------------
 [21] 1 @ Sniper Scav
 [22] 1 @ Sniper Scav
 [23] 1 @ Sniper Scav
------------------------ Raider ------------------------
 [24] 3-4 @ pmcBot
 [25] 3-4 @ pmcBot
 [26] 3-4 @ pmcBot
        bigmap @ Bots Generated / Total 26 Waves

  SHORELINE
  MaxBotPerZone: 20     MaxAlive: 20
------------------------- Boss -------------------------
 [¿] Secret
------------------------- PMC --------------------------
 [1] 1-5 @ PMC [USEC Chance: 50]
 [2] 1-5 @ PMC [USEC Chance: 50]
 [3] 1-5 @ PMC [USEC Chance: 50]
 [4] 1-5 @ PMC [USEC Chance: 50]
 [5] 1-5 @ PMC [USEC Chance: 50]
------------------------- Scav -------------------------
 [6] 1-3 @ Scav
 [7] 1-3 @ Scav
 [8] 1-3 @ Scav
 [9] 1-3 @ Scav
 [10] 1-3 @ Scav
 [11] 1-3 @ Scav
---------------------- Sniper Scav ---------------------
 [12] 1 @ Sniper Scav
 [13] 1 @ Sniper Scav
------------------------ Raider ------------------------
 [14] 3-4 @ pmcBot
 [15] 3-4 @ followerBully
        shoreline @ Bots Generated / Total 15 Waves

  INTERCHANGE
  MaxBotPerZone: 20     MaxAlive: 20
------------------------- Boss -------------------------
 [¿] Secret
------------------------- PMC --------------------------
 [1] 1-5 @ PMC [USEC Chance: 50]
 [2] 1-5 @ PMC [USEC Chance: 50]
 [3] 1-5 @ PMC [USEC Chance: 50]
 [4] 1-5 @ PMC [USEC Chance: 50]
 [5] 1-5 @ PMC [USEC Chance: 50]
------------------------- Scav -------------------------
 [6] 1-3 @ Scav
 [7] 1-3 @ Scav
 [8] 1-3 @ Scav
 [9] 1-3 @ Scav
 [10] 1-3 @ Scav
 [11] 1-3 @ Scav
------------------------ Raider ------------------------
 [12] 3-4 @ pmcBot
 [13] 3-4 @ followerGluharAssault
        interchange @ Bots Generated / Total 13 Waves

  REZERVBASE
  MaxBotPerZone: 20     MaxAlive: undefined
------------------------- Boss -------------------------
 [¿] Secret
------------------------- PMC --------------------------
 [1] 1-5 @ PMC [USEC Chance: 50]
 [2] 1-5 @ PMC [USEC Chance: 50]
 [3] 1-5 @ PMC [USEC Chance: 50]
 [4] 1-5 @ PMC [USEC Chance: 50]
 [5] 1-5 @ PMC [USEC Chance: 50]
------------------------- Scav -------------------------
 [6] 1-3 @ Scav
 [7] 1-3 @ Scav
 [8] 1-3 @ Scav
 [9] 1-3 @ Scav
 [10] 1-3 @ Scav
 [11] 1-3 @ Scav
------------------------ Raider ------------------------
 [12] 3-4 @ pmcBot
 [13] 3-4 @ pmcBot
        rezervbase @ Bots Generated / Total 13 Waves

  FACTORY4_DAY
  MaxBotPerZone: 100    MaxAlive: 15
------------------------- Boss -------------------------
 [¿] Secret
------------------------- PMC --------------------------
 [1] 1-3 @ PMC [USEC Chance: 50]
 [2] 1-3 @ PMC [USEC Chance: 50]
 [3] 1-3 @ PMC [USEC Chance: 50]
 [4] 1-3 @ PMC [USEC Chance: 50]
 [5] 1-3 @ PMC [USEC Chance: 50]
------------------------- Scav -------------------------
 [6] 1-3 @ Scav
 [7] 1-3 @ Scav
 [8] 1-3 @ Scav
 [9] 1-3 @ Scav
 [10] 1-3 @ Scav
        factory4_day @ Bots Generated / Total 10 Waves

  FACTORY4_NIGHT
  MaxBotPerZone: 100    MaxAlive: 15
------------------------- Boss -------------------------
 [¿] Secret
------------------------- PMC --------------------------
 [1] 1-3 @ PMC [USEC Chance: 50]
 [2] 1-3 @ PMC [USEC Chance: 50]
 [3] 1-3 @ PMC [USEC Chance: 50]
 [4] 1-3 @ PMC [USEC Chance: 50]
 [5] 1-3 @ PMC [USEC Chance: 50]
------------------------- Scav -------------------------
 [6] 1-3 @ Scav
 [7] 1-3 @ Scav
 [8] 1-3 @ Scav
 [9] 1-3 @ Scav
 [10] 1-3 @ Scav
        factory4_night @ Bots Generated / Total 10 Waves

  LABORATORY
  MaxBotPerZone: 20     MaxAlive: 20
------------------------- Boss -------------------------
 [¿] Secret
------------------------- PMC --------------------------
 [1] 1-5 @ PMC [USEC Chance: 50]
 [2] 1-5 @ PMC [USEC Chance: 50]
 [3] 1-5 @ PMC [USEC Chance: 50]
 [4] 1-5 @ PMC [USEC Chance: 50]
 [5] 1-5 @ PMC [USEC Chance: 50]
------------------------ Raider ------------------------
 [6] 3-4 @ pmcBot
 [7] 3-4 @ pmcBot
        laboratory @ Bots Generated / Total 7 Waves

  WOODS
  MaxBotPerZone: 20     MaxAlive: 20
------------------------- Boss -------------------------
 [¿] Secret
------------------------- PMC --------------------------
 [1] 1-5 @ PMC [USEC Chance: 50]
 [2] 1-5 @ PMC [USEC Chance: 50]
 [3] 1-5 @ PMC [USEC Chance: 50]
 [4] 1-5 @ PMC [USEC Chance: 50]
 [5] 1-5 @ PMC [USEC Chance: 50]
------------------------- Scav -------------------------
 [6] 1-3 @ Scav
 [7] 1-3 @ Scav
 [8] 1-3 @ Scav
 [9] 1-3 @ Scav
 [10] 1-3 @ Scav
 [11] 1-3 @ Scav
---------------------- Sniper Scav ---------------------
 [12] 1 @ Sniper Scav
 [13] 1 @ Sniper Scav
------------------------ Raider ------------------------
 [14] 3-4 @ pmcBot
 [15] 3-4 @ pmcBot
        woods @ Bots Generated / Total 15 Waves

  LIGHTHOUSE
  MaxBotPerZone: 20     MaxAlive: 20
------------------------- Boss -------------------------
 [¿] Secret
------------------------- PMC --------------------------
 [1] 1-5 @ PMC [USEC Chance: 50]
 [2] 1-5 @ PMC [USEC Chance: 50]
 [3] 1-5 @ PMC [USEC Chance: 50]
 [4] 1-5 @ PMC [USEC Chance: 50]
 [5] 1-5 @ PMC [USEC Chance: 50]
------------------------- Scav -------------------------
 [6] 1-3 @ Scav
 [7] 1-3 @ Scav
 [8] 1-3 @ Scav
 [9] 1-3 @ Scav
 [10] 1-3 @ Scav
 [11] 1-3 @ Scav
---------------------- Sniper Scav ---------------------
 [12] 1 @ Sniper Scav
 [13] 1 @ Sniper Scav
------------------------ Raider ------------------------
 [14] 3-4 @ pmcBot
 [15] 3-4 @ pmcBot
        lighthouse @ Bots Generated / Total 15 Waves
--------------------------------------------------------
Generated new bot spawns
Profile changes saved
[Client Request] /client/handbook/templates
[Client Request] /client/hideout/areas
[Client Request] /client/hideout/qte/list
[Client Request] /client/hideout/settings
[Client Request] /client/hideout/production/recipes
[Client Request] /client/hideout/production/scavcase/recipes
[Client Request] /client/handbook/builds/my/list
[Client Request] /client/notifier/channel/create
[Client Request] /client/profile/status
[Client Request] /client/friend/list
[Client Request] /client/friend/request/list/inbox
[Client Request] /client/mail/dialog/list
[Client Request] /client/friend/request/list/outbox
[Client Request] /client/trading/customization/storage
[WS] Player: d7c8cc12a6d36258c0309277 has connected
[Client Request] /client/server/list
[Client Request] /client/match/group/current
[Client Request] /client/quest/list
[Client Request] /client/repeatalbeQuests/activityPeriods
[Client Request] /launcher/profile/info
[Client Request] /launcher/server/version
[Client Request] /files/launcher/side_usec.png
[Client Request] /files/trader/avatar/59b91ca086f77469a81232e4.jpg
[Client Request] /files/trader/avatar/59b91cab86f77469aa5343ca.jpg
[Client Request] /files/trader/avatar/579dc571d53a0658a154fbec.jpg
[Client Request] /files/trader/avatar/59b91cb486f77469a81232e5.jpg
[Client Request] /files/trader/avatar/59b91cbd86f77469aa5343cb.jpg
[Client Request] /files/trader/avatar/5a7c2ebb86f7746e324a06ab.jpg
[Client Request] /files/trader/avatar/5ac3b86a86f77461491d1ad8.jpg
[Client Request] /files/trader/avatar/5c06531a86f7746319710e1b.jpg
[Client Request] /files/trader/avatar/AKGUY.jpg
[Client Request] /files/trader/avatar/DOC_TRADER.jpg
[Client Request] /files/trader/avatar/GearGal.jpg
[Client Request] /files/trader/avatar/GoblinKingMidJourneythumbnail.png
[Client Request] /files/trader/avatar/OUTFITTER.jpg
[Client Request] /files/trader/avatar/Priscilu.jpg
[Client Request] /files/trader/avatar/armalite.jpg
[Client Request] /files/trader/avatar/broker_portrait1.png
[Client Request] /client/checkVersion
[Client Request] /client/items/prices/54cb57776803fa99248b456e
[Client Request] /client/trading/api/getTraderAssort/54cb57776803fa99248b456e
Profile changes saved
[Client Request] /player/health/sync
[Client Request] /client/repeatalbeQuests/activityPeriods
Profile changes saved
Profile changes saved
[Client Request] /client/repeatalbeQuests/activityPeriods
[Client Request] /launcher/profile/info
[Client Request] /launcher/server/version
Profile changes saved
[Client Request] /client/items/prices/armalite
[Client Request] /client/trading/api/getTraderAssort/armalite
[Client Request] /client/game/logout
[Client Request] /launcher/profile/info
[Client Request] /launcher/server/version
[Client Request] /launcher/profile/remove
[Client Request] /launcher/server/connect
[Client Request] /launcher/ping
[Client Request] /launcher/server/version
[Client Request] /launcher/profiles
[Client Request] /launcher/ping

**Comment by space-commits** [comment] 2023-06-01 12:32
You have dozens of mods installed, many of which are outdated, and there is no indication that it is Realism mod causing the errors. I am closing this issue due to these factors. If you isolate Realism Mod and can reproduce the issue on the latest compatible version of SPT feel free to open another issue.

**Closed** 2023-06-01 12:33 UTC
