### ISSUE TITLE
[Bug] Overdose stim (SJ6)

### ISSUE THREAD

**Issue by Lol1chw** [space-commits/SPT-Realism-Mod-Client#58] opened 2024-05-11 08:54 UTC
# List versions
- SPT 3.8.1
- SPT Realism 1.2.0

# What is the expected behavior?
No overdose when SJ6 is discontinued.

# What do you see instead?
```Overdosed On Performance-Enhancing Stims```

# What steps can reproduce the bug?
1. Take the SJ6 stim on the raid.
2. Use SJ6.
    1. Cancel the animation of using SJ6.
4. Use SJ6 again.

[Reproduction video](https://www.youtube.com/watch?v=FGS-aBHfzLM)

**Comment by space-commits** [comment] 2024-05-12 15:18
Can you confirm if this happens with other stims? Does it happen if you cancel the stim twice and never take it?

**Comment by Lol1chw** [comment] 2024-05-15 04:02
`Can you confirm if this happens with other stims?` -
I've tested 21 stimulators and can confirm that this happens with a few others besides the SJ6. In the course of testing I also found a stimulator that behaved differently to all the others - AHF1-M, there were no side effects when overdosing on it.

`Does it happen if you cancel the stim twice and never let the animation complete?` - Yes

---
The following stims were not tested: 
- Antitoxin
- SJ15
- ObdolbosN

Table of stims tested

| Stim name        | Type           | Overdose  |
| ------------- |:-------------:| -----:|
| P22 | Damage | ❌ | 
| PNB Product 16 | Damage | ✔ |
| Propital | Regenerative | ❌ |
| eTG-change | Regenerative | ❌ |
| SJ0 | Regenerative | ✔ |
| Antidote xTG-12 | Generic | ❌ |
| SJ12 | Generic | ✔ |
| SJ9 | Generic | ❌ |
| Obdolbos-1 | Generic | ✔ |
| Obdolbos-2 | Generic | ✔ |
| Perfotoran (Blue Blood) | Generic | ❌ |
| SJ1 | Performance | ✔ |
| SJ6 | Performance | ✔ |
| 3-b-TG | Performance | ❌ |
| Meldonin | Performance | ❌ |
| Zagustin | Clotting | ❌ |
| AHF1-M | Clotting | ✔ no side effects |
| Trimadol | Adrenal | ❌ |
| L1 (Norepinephrine) | Adrenal | ❌ |
| Adrenaline | Adrenal | ❌ |
| M.U.L.E | Weight | ❌ |

[Tests video](https://youtu.be/-KEn1raALXs)

**Comment by space-commits** [comment] 2024-05-16 12:42
The issue is the delay. Med effects can only be cancelled if the effect hasn't activated yet, so the stims with effects with 0 delay can cause these issues. Solution should be to just add a minimum delay of 5 seconds before registering the stim for overdose effect.

**Comment by space-commits** [comment] 2024-05-18 12:26
closing now as it should be resolved

**Closed by space-commits** 2024-05-18 12:26 UTC
